// Rutas Ficheros
var PATH_FILE_EVOLUTION = './uploads/evolutions/';
var PATH_FILE_LEVEL = './uploads/levels/';

// Parámetros BBDD
var PORT = 3977;
var PORT_BBDD = 27017;
var TABLE_USER = 'USER';
var TABLE_ACTION = 'ACTION';
var TABLE_EVOLUTION = 'EVOLUTION';
var TABLE_GAME = 'GAME';
var TABLE_GOAL = 'GOAL';
var TABLE_LEARNING = 'LEARNING';
var TABLE_LEVEL_ACTION = 'LEVEL_ACTION';
var TABLE_LEVEL_GOAL = 'LEVEL_GOAL';
var TABLE_LEVEL_LEARNING = 'LEVEL_LEARNING';
var TABLE_LEVEL = 'LEVEL';

// Otros parámetros
var ID_FIRST_LEVEL = '5a7c987d3e62ed6ebe9431d5';
var ID_USER_ADMIN = '5a7432e8426ca91f60bafc6a';
var TOKEN_KEY = 'C0D3-3V0LUT10N';

module.exports = {
    PATH_FILE_EVOLUTION,    
    PATH_FILE_LEVEL,        
    PORT,
    PORT_BBDD,
    TABLE_USER,
    TABLE_ACTION,
    TABLE_EVOLUTION,
    TABLE_GAME,
    TABLE_GOAL,
    TABLE_LEARNING,
    TABLE_LEVEL_ACTION,
    TABLE_LEVEL_GOAL,
    TABLE_LEVEL_LEARNING,
    TABLE_LEVEL,
    ID_FIRST_LEVEL,
    ID_USER_ADMIN,
    TOKEN_KEY
};